### ISSUE TITLE
SQLSTATE[HY000]: General error: 1096 No tables used The SQL being executed was: SELECT *

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/active-record#23]
### What steps will reproduce the problem?
When the query is executed in the model, it returns the error yii \ db \ Exception: SQLSTATE [HY000]: General error: 1096 No tables used.

### What is the expected result?
The execution of the query

### Additional info
ActiveRecord.php correctly loads the schema, but ActiveQuery.php the connection information is null.

```
Next yii\db\Exception: SQLSTATE[HY000]: General error: 1096 No tables used
The SQL being executed was: SELECT * in /home/app.cjtterabyte.com/public_html/vendor/yiisoft/db/src/Schema.php:664
Stack trace:
#0 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/db/src/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT *')
#1 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/db/src/Command.php(1148): yii\db\Command->internalExecute('SELECT *')
#2 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/db/src/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/db/src/Query.php(274): yii\db\Command->queryOne()
#4 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/active-record/src/ActiveQuery.php(296): yii\db\Query->one(NULL)
#5 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/active-record/src/BaseActiveRecord.php(111): yii\activerecord\ActiveQuery->one()
#6 /home/app.cjtterabyte.com/public_html/vendor/terabytesoft/app-basic/src/forms/UserForm.php(95): yii\activerecord\BaseActiveRecord::findOne(Array)
#7 /home/app.cjtterabyte.com/public_html/vendor/terabytesoft/app-basic/src/forms/LoginForm.php(104): app\basic\forms\UserForm::findByUsername('tecnologiaterab...')
#8 /home/app.cjtterabyte.com/public_html/vendor/terabytesoft/app-basic/src/forms/LoginForm.php(74): app\basic\forms\LoginForm->getUser()
#9 [internal function]: app\basic\forms\LoginForm->validatePassword('password', NULL, Object(yii\validators\InlineValidator))
#10 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/validators/InlineValidator.php(72): call_user_func(Array, 'password', NULL, Object(yii\validators\InlineValidator))
#11 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/validators/Validator.php(274): yii\validators\InlineValidator->validateAttribute(Object(app\basic\forms\LoginForm), 'password')
#12 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/base/Model.php(364): yii\validators\Validator->validateAttributes(Object(app\basic\forms\LoginForm), Array)
#13 /home/app.cjtterabyte.com/public_html/vendor/terabytesoft/app-basic/src/forms/LoginForm.php(87): yii\base\Model->validate()
#14 /home/app.cjtterabyte.com/public_html/vendor/terabytesoft/app-basic/src/controllers/SiteController.php(99): app\basic\forms\LoginForm->login()
#15 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/base/InlineAction.php(56): app\basic\controllers\SiteController->actionLogin()
#16 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#17 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('login', Array)
#18 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('site/login', Array)
#19 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /home/app.cjtterabyte.com/public_html/public/index.php(11): yii\base\Application->run()
#21 /home/app.cjtterabyte.com/public_html/public/index.php(12): {closure}()
#22 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1096
    [2] => No tables used
)
```

| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      |  7.1.23
| Operating system | Centos 7

https://github.com/yiisoft/db/issues/1

**Comment by machour** [comment]
Seeing this too when running tests on db-xxxx packages

**Comment by machour** [comment]
Running tests in `yiisoft/yii-twig` is a good way to reproduce this "really blocking" problem. 
[Travis log](https://travis-ci.org/yiisoft/yii-twig/jobs/472805632)
